AutoMobile/AutoMobile/Controllers/AdvertiseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web.WebPages;
using AutoMobile.Models;
using Microsoft.Ajax.Utilities;
using Model;
using Business_Logic_Layer;
using System.Web.Mvc;

namespace AutoMobile.Controllers
{
    public class AdvertiseController : Controller
    {
        private readonly AdvertiseLogic _advertiselogic;
        private readonly UserLogic _userLogic;
        private readonly BrandLogic _brandLogic;
        private static readonly int AdvertsPerPage;
        private static readonly int RenewMonthsValidAdvert;

        static AdvertiseController()
        {
            AdvertsPerPage = Int32.Parse(@System.Web.Configuration.WebConfigurationManager.AppSettings["AdvertsPerPage"]);

            int NDaysValidAfterExpired =
                Int32.Parse(@System.Web.Configuration.WebConfigurationManager.AppSettings["NDaysValidAfterExpired"]);
            AdvertiseLogic.SetDaysUntilTerminate(NDaysValidAfterExpired);

            RenewMonthsValidAdvert = Int32.Parse(@System.Web.Configuration.WebConfigurationManager.AppSettings["MonthsValidAdvert"]);
        }

        public AdvertiseController(AdvertiseLogic s, UserLogic u, BrandLogic b)
        {
            _advertiselogic = s;
            _userLogic = u;
            _brandLogic = b;
        }

        // GET: /Advertise/
        public ActionResult Index(int? page)
        {
            if (!page.HasValue) page = 0;
            IEnumerable<IGrouping<String, Advert>> groupEnumerable =
                _advertiselogic.GetAllOpenByBrandPaged(page.Value, AdvertsPerPage);
            return View("List", groupEnumerable);
        }

        //GET /Advertise/Detailed/{id}
        public ActionResult Detailed(int? id)
        {
            if (!id.HasValue) return RedirectToActionPermanent("Index");

            Advert advert = _advertiselogic.GetAdvert(id.Value);
            if (advert == null) return View("List");
            User u = _userLogic.GetUserById(advert.AdvertiseOwner);
            ViewBag.user = u;

            ViewData["email"] = u.Email;

            return View(advert);

        }

        //POST /Advertise/Comment/
        //[HttpPost]

        [AcceptVerbs("POST")]
        [Authorize]
        public ActionResult Comment(Comment comment, string url)
        {
            if (!ModelState.IsValid) return RedirectToAction("Detailed", new {id = comment.AdId});

            if (!_advertiselogic.AddCommentary(comment))
            {
                ModelState.AddModelError("", "Não foi possível enviar o email.");
                return RedirectToAction("Detailed/" + comment.AdId);
            }
               
            Advert advert = _advertiselogic.GetAdvert(comment.AdId);
            User owner = _userLogic.GetUserById(advert.AdvertiseOwner);

            MailMessage mail = new MailMessage();
            mail.To.Add(owner.Email);

            User activeUser = _userLogic.GetUserById(User.Identity.Name);
            mail.From = new MailAddress(activeUser.Email);
            mail.Subject = "Comentário sobre o seu carro: " + advert.Brand + " " + advert.Model;

            string Body = comment.Username + " deu " + comment.Rating +" estrelas ao seu carro!<br>";
            if (@Request.Url != null)
                Body += url + "<br><br>";
            Body += comment.Message;               
            mail.Body = Body;
 
            if (!_advertiselogic.sendMail(mail))
                ModelState.AddModelError("", "Não foi possível enviar o email.");

            return RedirectToAction("Detailed/" + comment.AdId);
        }

        //[HttpPost]
        [AcceptVerbs("POST")]
        public ActionResult VendorContact(MailModel mailModel)
        {
            if (!ModelState.IsValid) return View("Detailed");

            Advert advert = _advertiselogic.GetAdvert(mailModel.AdId);
            User owner = _userLogic.GetUserById(advert.AdvertiseOwner);
            MailMessage mail = new MailMessage();
            mail.To.Add(owner.Email);
            mail.From = new MailAddress(mailModel.From);
            mail.Subject = "Um utilizador do AutoMobile enviou-lhe uma mensagem";
            mail.Body = mailModel.Message + "<br>" +
                        mailModel.From + "<br>" +
                        mailModel.Name + ", " + mailModel.Phone;

            if(!_advertiselogic.sendMail(mail))
                ModelState.AddModelError("", "Não foi possível enviar o email.");

            return RedirectToAction("Detailed/" + mailModel.AdId);
        }

        //GET /Advertise/Add/{id}
        [Authorize]
        public ActionResult Add()
        {
            ViewData["Brand"] = new SelectList(_brandLogic.GetAllBrands(true));
            //ViewData["BrandJson"] = _brandLogic.GetAllBrandsJsonToddSlick();
            return View();
        }
        //POST /Advertise/Add/{id}
        [Authorize]
        [HttpPost]
        public ActionResult Add(Advert a)
        {
            ViewData["Brand"] = new SelectList(_brandLogic.GetAllBrands(true));
            if (!ModelState.IsValid) return View();
            _advertiselogic.AddAdvert(a); //TODO fazer verificações
            _userLogic.AssociateAdvertToUser(a.Id, User.Identity.Name);
            return RedirectToAction("Detailed", new { id = a.Id });
        }
        //GET /Advertise/Edit/{id}
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (!id.HasValue) return RedirectToAction("ManageAd", "Account");
            Advert advert = _advertiselogic.GetAdvert(id.Value);
            User u = _userLogic.GetUserById(advert.AdvertiseOwner);
            ViewBag.advert = advert;
            return View(u);
        }
        //POST /Advertise/Edit/{id}
        [Authorize]
        [HttpPost]
        public ActionResult Edit(int? id, float Price, bool? Negotiable, String Description, String Password)
        {
            User activeUser = _userLogic.GetUserById(User.Identity.Name);
            if (Password.IsNullOrWhiteSpace() || !activeUser.Password.Equals(Password))
            {
                ModelState.AddModelError("badPassword", "Password errada!");
                return RedirectToAction("Edit");
            }
            Advert advert;
            if (id.HasValue && !(advert = _advertiselogic.GetAdvert(id.Value)).Equals(null))
            {
                if (!advert.Price.Equals(Price) && Price > 0)
                    advert.Price = Price;
                if (Negotiable.HasValue && advert.Negotiable != Negotiable.Value)
                    advert.Negotiable = Negotiable.Value;
                if (!Description.IsNullOrWhiteSpace() && !advert.Description.Equals(Description))
                    advert.Description = Description;

                if (_advertiselogic.UpdateAdvert(advert))
                    return RedirectToAction("ManageAd", "Account");
            }
            ModelState.AddModelError("AdvertUpdateError", "Erro! Não foi possível editar este anúncio!");
            return RedirectToAction("Edit");

        }
        //POST /Advertise/Cancel/{id}
        [Authorize]
        public ActionResult Cancel(int? id)
        {
            if (!id.HasValue) return RedirectToAction("ManageAd", "Account");
            Advert advert = _advertiselogic.GetAdvert(id.Value);

            advert.Status = AdvertStatusEnum.Cancelado;
            _advertiselogic.UpdateAdvert(advert);

            return RedirectToAction("ManageAd", "Account");
        }

        //POST /Advertise/Activate/{id}
        [Authorize]
        public ActionResult Activate(int? id)
        {
            if (!id.HasValue) return RedirectToAction("ManageAd", "Account");
            Advert advert = _advertiselogic.GetAdvert(id.Value);
            if (advert.Status == AdvertStatusEnum.Expirado || advert.Status == AdvertStatusEnum.Terminado)
                advert.ValidUntil = DateTime.Now.AddMonths(RenewMonthsValidAdvert);

            advert.Status = AdvertStatusEnum.Ativo;
            _advertiselogic.UpdateAdvert(advert);

            return RedirectToAction("ManageAd", "Account");
        }
        //POST /Advertise/Delete/{id}
        [Authorize]
        [HttpPost]
        public ActionResult Delete(int? id)
        {
            if (ModelState.IsValid && id.HasValue)
            {
                Advert advert = _advertiselogic.GetAdvert(id.Value);
                if (_advertiselogic.DeleteAdvert(advert))
                    return RedirectToAction("ManageAd", "Account");
            }
            ModelState.AddModelError("Advert", "That advertise couldn't be removed");
            return RedirectToAction("ManageAd", "Account");
        }

        [HttpGet]
        public ActionResult GetModelsByBrand(string brand)
        {
            if (Request.IsAjaxRequest() && !brand.IsEmpty())
            {
                CarBrand carBrand = _brandLogic.getModelsFromBrand(brand);
                if (carBrand != null)
                    return Json(carBrand.models.ToList(), JsonRequestBehavior.AllowGet);
            }

            return new JsonResult
            {
                Data = "Not Valid Request",
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
 
        }


        //GET /Advertise/Search
        [HttpGet]
        public ActionResult Search(String brand)
        {
            ViewData["MaxPrice"] = _advertiselogic.GetMaxPrice();
            ViewData["MinPrice"] = _advertiselogic.GetMinPrice();
            ViewData["MaxKm"] = _advertiselogic.GetMaxKm();
            ViewData["MinKm"] = _advertiselogic.GetMinKm();
            ViewData["MaxYear"] = _advertiselogic.GetMaxYear();
            ViewData["MinYear"] = _advertiselogic.GetMinYear();

            ViewData["Brand"] = new SelectList(_brandLogic.GetAllBrands(true));

            return View();
        }

        //GET /Advertise/Search/filters
        [HttpGet]
        public ActionResult Searched(FilterAdvertise fa)
        {

AutoMobile/AutoMobile/Views/Shared/PartialCharacteristics.cshtml
@model Model.Characteristics

@{     
     for (int i = 0; i < @Model.Length; i++)
     {
         var element = @Model.GetElement(i);
         string url = element.Has ? @String.Format("~/Content/images/CarCharacteristics/a{0}.jpg", i + 1) : "~/Content/images/CarCharacteristics/a0.jpg";
         url = Url.Content(url);
         <img src="@url" width="21" title="@element.Title" /> //add class to put width 21 in css
         
     }
 }

AutoMobile/AutoMobile/Views/Shared/PartialCharacteristicsForm.cshtml
@using AutoMobile


@Html.MyCharacteristics(Url.Content("~/Content/images/CarCharacteristics/a1.jpg"), "Ar Condicionado", @Html.CheckBox("HasConditionAir").ToHtmlString())
@Html.MyCharacteristics(Url.Content("~/Content/images/CarCharacteristics/a2.jpg"), "Direcção Assistida", @Html.CheckBox("HasAssistedDirection").ToHtmlString())
@Html.MyCharacteristics(Url.Content("~/Content/images/CarCharacteristics/a3.jpg"), "Vidros Eléctricos", @Html.CheckBox("HasElectricGlass").ToHtmlString())
@Html.MyCharacteristics(Url.Content("~/Content/images/CarCharacteristics/a4.jpg"), "Fecho Eléctrico", @Html.CheckBox("HasElectricClose").ToHtmlString())
@Html.MyCharacteristics(Url.Content("~/Content/images/CarCharacteristics/a5.jpg"), "Sistema de som", @Html.CheckBox("HasSoundSystem").ToHtmlString())
@Html.MyCharacteristics(Url.Content("~/Content/images/CarCharacteristics/a6.jpg"), "Caixa Automática", @Html.CheckBox("HasAutomaticBox").ToHtmlString())
@Html.MyCharacteristics(Url.Content("~/Content/images/CarCharacteristics/a7.jpg"), "Tracção às 4 Rodas", @Html.CheckBox("Has4WheelsTraction").ToHtmlString())

AutoMobile/AutoMobile/Views/Shared/PartialCommentary.cshtml
@model Model.Comment



                   @* Outra versao*@      
@*                        <h3 class="list-group-item-heading">@(Model.Username) / *@
@*                            <small> dia: </small></h3>*@
@**@
@*                        <p class="list-group-item-text">@(Model.Message)</p>*@
                        


<div class="center-block">
<tr>
    <td>@Model.Username</td>
    <td><span class="badge">@Model.Rating<span class="glyphicon glyphicon-star"></span></span></td>
    @*    <td>@Model.Date</td>*@
    <td id="ratingDescr">@Model.Message</td>
</tr>
    </div>

AutoMobile/AutoMobile/Views/Shared/PartialDropdownAdvertStatusEnum.cshtml
@using Model

@{
    var status = from AdvertStatusEnum e in Enum.GetValues(typeof(AdvertStatusEnum)) select e;
    @Html.DropDownList("Status", new SelectList(status),"Selecciona", new {@class="form-control"})
    
} 

AutoMobile/AutoMobile/Views/Shared/PartialDropdownDistrictEnum.cshtml
@using Model

@{ 
    
    var districts = from DistrictEnum e in Enum.GetValues(typeof(DistrictEnum)) select new { Id = e, Name = e.ToString().Replace('_',' ') };
    @Html.DropDownList("District", new SelectList(districts, "Id", "Name"),"Seleccione",new {@class="form-control"} )
    
} 

AutoMobile/AutoMobile/Views/Shared/PartialDropdownFuelTypeEnum.cshtml
@using Model

@{
    var fuels = from FuelTypeEnum e in Enum.GetValues(typeof(FuelTypeEnum)) select new { Id = e, Name = e.ToString().Replace('_', ' ') };
    @Html.DropDownList("FuelType", new SelectList(fuels, "Id", "Name"),"Seleccione", new {@class="form-control"})
    
} 

AutoMobile/AutoMobile/Views/Shared/PartialListAdvertWithCharacteristics.cshtml
@model Model.Advert


<tr id="@String.Format("car{0}", @Model.Id)">
    <td>
        <img class="advertiseImage" src="~/Content/images/CarPhotos/@Model.Photos.First.Value.Link"></td>
    <td>
        <p class="advertData"><a href="@Url.Action("Detailed", "Advertise", new {id = @Model.Id})">@Model.Brand @Model.Model @Model.Version : @Model.Kilometers Km's</a></p>
        <p class="fuelType advertData">@Model.Year - @Model.FuelType.ToString().Replace('_',' ') - @Model.averageRate <span class="glyphicon glyphicon-star"></span></p>
    </td>
    <td>@Model.Price.000 €</td>
    <td>
        @Html.Partial("PartialCharacteristics", Model.Characteristics)
    </td>
</tr>

AutoMobile/AutoMobile/Views/Shared/PartialListAdvertWithUserOpers.cshtml
@model Model.Advert


<tr id="@String.Format("car{0}", @Model)">
    <td>
        <img class="advertiseImage" src="~/Content/images/CarPhotos/@Model.Photos.First.Value.Link"></td>
    <td>
        <p class="advertData"><a href="@Url.Action("Detailed", "Advertise", new {id = @Model.Id})">@Model.Brand @Model.Model @Model.Version : @Model.Kilometers Km's</a></p>
        <p class="fuelType advertData">@Model.Year - @Model.FuelType.ToString().Replace('_',' ')</p>
    </td>
    <td>@Model.Price.000 €</td>
    @Html.Partial("PartialUserOpers")

</tr>

AutoMobile/AutoMobile/Views/Shared/PartialPagination.cshtml
@using System.Globalization
@model int
@{
    ViewBag.Title = "PartialPaginationView";
}

<div id="pagination">
    <ul class="pagination">

        @{
            var reqUri = @HttpUtility.ParseQueryString(@Url.RequestContext.HttpContext.Request.QueryString.ToString());
            //var validPage = !String.IsNullOrWhiteSpace(reqUri["page"]);
            var maxPages = @Model;
            var @blink = "?" + (Convert.ToInt32(reqUri["page"]) - 1);
            var @alink = "?" + (Convert.ToInt32(reqUri["page"]) + 1);
            var @isFirstPage = Convert.ToInt32(reqUri["page"]) == 0;
            var @isLastPage = Convert.ToInt32(reqUri["page"]) == maxPages;
            //var @actualPage = Convert.ToInt32(reqUri["page"]);
        }         
        @if (@isFirstPage){         <li class="disabled"><a href="#">&laquo;</a></li>   }
        else{                       <li><a href="@blink">&laquo;</a></li>   }
               
        @for (int i = 0; i <= maxPages; i++){

            reqUri["page"] = @i.ToString(CultureInfo.InvariantCulture);
            var link =/* @Url.Action("") */ "?" + reqUri;
                
            <li><a href="@link">@(i+1)</a></li>
        }
        @*if (actualPage == i){   <li class="active"><a href="@link">@(i+1)</a></li>}*@

        @if (@isLastPage){          <li class="disabled"><a href="#">&raquo;</a></li>}
        else{                       <li><a href="@alink">&raquo;</a></li>}    
        
    </ul>
</div>

AutoMobile/AutoMobile/Views/Shared/PartialUserOpers.cshtml
@using Model
@model Model.Advert


<td>
    <div id ="statusManageAd">
        @if (Model.Status == AdvertStatusEnum.Expirado){
            <span class="label label-warning">@Html.Label(Model.Status.ToString())</span>
        }
        else if (Model.Status == AdvertStatusEnum.Cancelado){
            <span class="label label-danger">@Html.Label(Model.Status.ToString())</span>  
        }
        else if (Model.Status == AdvertStatusEnum.Terminado){
            <span class="label label-default">@Html.Label(Model.Status.ToString())</span>  
        }
        else{
            <span class="label label-success">@Html.Label(Model.Status.ToString()) até @Model.ValidUntil.ToString("dd/MM/yyyy")</span>
        }          
    </div>
    <a href="@Url.Action("Edit","Advertise",new{id=@Model.Id})"><img src="@Url.Content("~/Content/Images/UserManageIcons/pencil-icon.png")" title="Edita o anúncio"/></a>
    @if (Model.Status == AdvertStatusEnum.Ativo){
        <a href="@Url.Action("Cancel", "Advertise", new {id = @Model.Id})"><img src="@Url.Content("~/Content/Images/UserManageIcons/Button-Stop-icon.png")" title="Cancela o anúncio" /></a>
    }
    else{
        <a href="@Url.Action("Activate","Advertise",new{id=@Model.Id})"><img src="@Url.Content("~/Content/Images/UserManageIcons/Accept-icon.png")" title="Ativa o anúncio" /></a>
    }      
    <a onclick="checkDeleteAdvertise(@Model.Id)"><img src="@Url.Content("~/Content/Images/UserManageIcons/Quit-icon.png")" title="Apaga o anúncio" /></a>

</td>

AutoMobile/AutoMobile/Views/Shared/_AccountLayout.cshtml
@model  Model.User
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <meta name="viewport" content="width=device-width" />
        <title>@ViewBag.Title</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <link href="~/Content/css/global.css" rel="stylesheet" media="screen">
        <link href="~/Content/images/logo.ico" rel="SHORTCUT ICON" />
        <script src="~/Scripts/jquery-2.1.0.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
        <script>
            window.onload = function() {

                @if (IsSectionDefined("callOnLoadFuncs"))
                {
                    @RenderSection("callOnLoadFuncs")
                    ;
                }

            };
        </script>
        @if (IsSectionDefined("headScript"))
        {
            @RenderSection("headScript")
        }
    </head>
    <body>

        <!-- Fixed Navbar -->
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="@Url.Action("Index", "Home")">
                        <p class="navbar-brand">AutoMobile</p>
                    </a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="@Url.Action("Index", "Advertise")">Anúncios</a></li>
                        <li><a href="@Url.Action("Search", "Advertise")">Procurar</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                    @if (!User.Identity.IsAuthenticated)
                     {
                         <li><a href="@Url.Action("LogIn","Account")">Log In</a></li>
                         <li><a href="@Url.Action("Create","Account")">Registar</a></li>
                     }
                    else
                    {
                        <li><a href="@Url.Action("Index","Account")">Gerir Conta</a></li>
                        <li><a href="@Url.Action("Logout","Account")">Log Out</a></li>  
                    }
                </ul>
                </div>
            </div>
        </div>
        <!--Navbar -->
        <div class="container">
        <div class="col-md-3" >
            <div class="row" >
                <ul class="list-unstyled">
                    <li class="nav-header"> <a href="#" data-toggle="collapse" data-target="#userMenu">
                                                <h5>Settings <i class="glyphicon glyphicon-chevron-down"></i></h5>
                                            </a>
                        <ul class="list-unstyled collapse in" id="userMenu">
                            <li class="active"> <a href="@Url.Action("Index", "Account")"><i class="glyphicon glyphicon-home"></i> Home</a></li>
                            <li><a href="@Url.Action("Inbox", "Account")"><i class="glyphicon glyphicon-envelope"></i> Mensagens <span class="badge badge-info">4</span></a></li>
                            <li><a href="@Url.Action("Edit", "Account")"><i class="glyphicon glyphicon-cog"></i> Editar Conta</a></li>
                            <li><a href="@Url.Action("ManageAd","Account")"><i class="glyphicon glyphicon-wrench"></i> Gerir Anúncios</a></li>
                            <li><a href="@Url.Action("Add","Advertise")"><i class="glyphicon glyphicon-plus-sign"></i> Adicionar Anúncio</a></li>
                            <li><a href="@Url.Action("Logout","Account")"><i class="glyphicon glyphicon-off"></i> Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div></div>
        <div class="col-md-8">
            @RenderBody()
        </div>
            </div>
        <br />
        <footer><span class="label label-default">Copyright G05 PI 13/14 SVer. All Rights Reserved.</span></footer>
    </body>
</html>

AutoMobile/AutoMobile/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="~/Content/css/global.css" rel="stylesheet" media="screen">
    <link href="~/Content/images/icon.ico" rel="SHORTCUT ICON" />
    <script src="~/Scripts/jquery-2.1.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.ddslick.min.js"></script>

    <script type="text/javascript" src="~/Scripts/bootstrap-slider.js"></script>
    <script>
        window.onload = function () {

            $(document).ready(function () {
                /*TODO meter num ficheiro à parte */
                $(".sliderClicker").slider().on('slideStop', function (ev) {
                    var sliderElement = this;
                    var sliderID = sliderElement.attributes["data-slider-id"].value;
                    var y = $("#" + sliderID + " .tooltip-inner")[0].innerText;
                    var values = y.split(":");
                    var startFormId = "Start" + sliderID;
                    var endFormId = "End" + sliderID;

                    var startForm = $("#" + startFormId)[0];
                    var endForm = $("#" + endFormId)[0];
                    startForm.value = values[0].trim();

                    if (endForm && values[1]) {
                        endForm.value = values[1].trim();
                    }

                    console.log("Slider id: " + sliderID + ", start: " + startForm.value + ", end: " + endForm.value);
                });
            });
            @if (IsSectionDefined("callOnLoadFuncs"))
            {
                @RenderSection("callOnLoadFuncs");
            }
        };
    </script>
    @if (IsSectionDefined("headScript"))
    {
        @RenderSection("headScript")
    }
</head>
<body>

    <!-- Fixed Navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index","Home")">
                    <p class="navbar-brand">AutoMobile</p>
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index","Advertise")">Anúncios</a></li>
                    <li><a href="@Url.Action("Search","Advertise")">Procurar</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (!User.Identity.IsAuthenticated)
                     {
                        <li><a href="@Url.Action("LogIn","Account")">Log In</a></li>
                        <li><a href="@Url.Action("Create","Account")">Registar</a></li>
                     }
                    else
                    {
                         <li><a href="@Url.Action("Index","Account")">Gerir Conta</a></li> 
                         <li><a href="@Url.Action("Logout","Account")">Log Out</a></li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <!--Navbar -->

    @RenderBody()
    <br />
    <footer><span class="label label-default">Copyright G05 PI 13/14 SVer. All Rights Reserved.</span></footer>
</body>
</html>